version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: proylm_mysql  # Nombre del contenedor
    restart: always
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "sh", "-c", "mysql -h localhost -u root -p${MYSQL_ROOT_PASSWORD} -e 'SELECT 1'"]
      timeout: 20s
      retries: 10
    networks:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proylm_backend
    command: >
      sh -c "
        ./wait-for-it.sh db:3306 --timeout=60 --strict -- echo 'MySQL is ready!';
        python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python3 manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      MYSQL_HOST: 'db'
      MYSQL_ROOT_PASSWORD: Basketball01$
      MYSQL_DATABASE: gestor_recetas
      MYSQL_USER: nineck
      MYSQL_PASSWORD: Basketball01$
      MYSQL_PORT: 3306
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - backend


volumes:
  data:

networks:
  backend:
    driver: bridge
