# Generated by Django 5.1.3 on 2024-11-06 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ingredientes', models.TextField()),
                ('preparacion', models.TextField()),
                ('tiempo_preparacion', models.IntegerField()),
                ('dificultad', models.CharField(choices=[('fácil', 'Fácil'), ('intermedia', 'Intermedia'), ('difícil', 'Difícil')], max_length=50)),
                ('etiquetas', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
